spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pruedaesntt/bootCamp-ConfigServer
          default-label: main
          search-paths: 
          - '*yaml'
          
server:
  port: 8888
 